# Generated by Django 6.0 on 2025-12-27 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QnALog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='General', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('question_text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='qna_images/')),
                ('ai_answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
