# Generated by Django 6.0 on 2026-01-12 07:36
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("archiver", "0001_initial"),
    ]

    operations = [
        TrigramExtension(),
    ]
