# Generated by Django 6.0 on 2025-12-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qnalog',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='검증 완료'),
        ),
    ]
