# Generated by Django 6.0 on 2025-12-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0002_qnalog_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qnalog',
            name='ai_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
