# Generated by Django 6.0 on 2026-01-01 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0002_qnalog_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='qnalog',
            name='hit_count',
            field=models.PositiveIntegerField(default=1, verbose_name='질문 빈도'),
        ),
        migrations.AddField(
            model_name='qnalog',
            name='notion_page_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='노션 페이지 링크'),
        ),
        migrations.AddField(
            model_name='qnalog',
            name='parent_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_questions', to='archiver.qnalog'),
        ),
        migrations.AddField(
            model_name='qnalog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
