# Generated by Django 6.0 on 2026-01-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0004_qnalog_hit_count_qnalog_notion_page_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qnalog',
            name='keywords',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='추출된 키워드'),
        ),
    ]
