# Generated by Django 6.0 on 2026-01-05 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0003_qnalog_hit_count_qnalog_notion_page_url_and_more'),
        ('archiver', '0005_qnalog_keywords'),
    ]

    operations = [
    ]
