# Generated by Django 6.0 on 2026-01-07 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiver', '0006_merge_20260105_0906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qnalog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Q&A Log', 'verbose_name_plural': 'Q&A 로그 목록'},
        ),
        migrations.RemoveField(
            model_name='qnalog',
            name='keywords',
        ),
        migrations.AlterField(
            model_name='qnalog',
            name='category',
            field=models.CharField(choices=[('Git', 'Git'), ('Linux', 'Linux'), ('DB', 'DB'), ('Python', 'Python'), ('Flask', 'Flask'), ('Django', 'Django'), ('FastAPI', 'FastAPI'), ('General', 'General')], default='General', max_length=50, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='qnalog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='qnalog',
            name='parent_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_questions', to='archiver.qnalog', verbose_name='상위 질문'),
        ),
        migrations.AlterField(
            model_name='qnalog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
    ]
